### PR TITLE
Change the lowering option for vector.multi_reduction from InnerParallel to InnerReduction.

### PR DESCRIPTION
**Pull request by Kuigesi**

### CODE REVIEW

**Comment by Kuigesi** [comment]
vector.multi_reduction has two lowering setting: InnerParallel and InnerReduction.

vector.multi_reduction will transpose the input so that all reduction dimensions are either innermost or outermost.

InnerParallel will make the outermost dimension the reduction dimension, therefore lower to element-wise arith::op to aggregate the results.

InnerReduction will make the innermost dimension the reduction dimension, therefore lower to vector.reduction and eventually llvm.vector.reduce.* Intrinsic.

For example, if we reduce over a 2-D M x N tensor a by tl.sum(a, 1). 
If we use inner parallel, it will first transpose a to N x M, then generate N fadd<M x float>.
If we use inner reduction, it will generate M llvm.vector.reduce.fadd.v{N}f32.

For 1-D case, inner parallel will generate multiple scalar arithmetic instructions while inner reduction will generate a single llvm.vector.reduce instruction.

**Comment by embg** [comment]
> For 1-D case, inner parallel will generate multiple scalar arithmetic instructions while inner reduction will generate a single llvm.vector.reduce instruction.

I'm curious how the final x86 assembly differs? In other words, does `llvm.vector.reduce` ultimately lower to better codegen?

Also: should we have a lit test? Or has the infrastructure for lit tests not been added yet for triton-cpu?

**Comment by Kuigesi** [comment]
> > For 1-D case, inner parallel will generate multiple scalar arithmetic instructions while inner reduction will generate a single llvm.vector.reduce instruction.
> 
> I'm curious how the final x86 assembly differs? In other words, does `llvm.vector.reduce` ultimately lower to better codegen?
> 
> Also: should we have a lit test? Or has the infrastructure for lit tests not been added yet for triton-cpu?

Yes, so combined with fast-math, llvm.vector.reduce and the fmul are fused into vfmadd231ps on zmm registers. But the scalar arithmetic instructions are not fused.

For the lit test, I am not sure we currently have the infrastructure for it.

**Review by embg — APPROVED** [review]
Reviewed the LLVM and x86 listings you provided offline, it seems like this option does improve code-gen. Nice work!

**Pull request merged**
