### PR TITLE
[cpu] Have MulhiUI lowering support scalars

### PR DESCRIPTION
**Pull request by int3**
This makes most of the int32 tests in test_random.py pass. (int64 ones are still failing.)

Fixes https://github.com/triton-lang/triton-cpu/issues/62.

### CODE REVIEW

**Comment by int3** [comment]
I expect we might want to do the same for `ConstantOpConversion` in the same file. Would also be nice to have the code be more generic in general, instead of having every pattern handle both tensors and scalars manually... suggestions welcome!

**Review by minjang — APPROVED** [review]
Thanks!

**Comment by minjang** [comment]
> I expect we might want to do the same for `ConstantOpConversion` in the same file. Would also be nice to have the code be more generic in general, instead of having every pattern handle both tensors and scalars manually... suggestions welcome!

I'm perfectly fine to have some templates (even [macros](https://github.com/triton-lang/triton-cpu/blob/c9575d8146db0ef19d440fc7ac8995ac62829ffb/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp#L254-L269)) for the refactoring.

**Comment by ienkovich** [comment]
> I expect we might want to do the same for `ConstantOpConversion` in the same file. Would also be nice to have the code be more generic in general, instead of having every pattern handle both tensors and scalars manually... suggestions welcome!

The difference in tensor/vector and scalar code handling is usually in building types and constants. In fp8 conversion decomposition code, I used a set of helpers to get more compact code (GPU backend uses a similar set but for LLVM dialect) that can handle scalars and vectors. In this case, you could use [cst_like](https://github.com/triton-lang/triton-cpu/blob/main/third_party/cpu/lib/TritonCPUTransforms/OptCommon.h#L107) and [toInt32 ](https://github.com/triton-lang/triton-cpu/blob/main/third_party/cpu/lib/TritonCPUTransforms/OptCommon.h#L55C13-L55C20) to get a simpler version of the code.

**Pull request merged**
