### PR TITLE
[CPU] Move all llvm dependent code into triton_cpu.cc, add LLJIT, support macos and arm

### PR DESCRIPTION
**Pull request by Kuigesi**
1. Move all llvm dependent code into triton_cpu.cc to avoid double registration of llvm passes. Previous we also link llvm library into cpu_utils.so, which may lead to some static variables be initialized twice, causing the double registration issue.
2. Use off-the -shelf LLJIT to load bitcode and just-in-time compile it. The old version has bugs in the codegen pass with certain arm cpu (neoverse-v2).
3. Support mac m1
4. Support arm cpu (neoverse-v2) for linux.

### CODE REVIEW

**Comment by Kuigesi** [comment]
Perf result of running un-masked matrix-multiplication example on arm neoverse-v2:

```
(base) [ruiqigao@devarm001.atn1 ~/ruiqi/triton-cpu (add-lljit)]$ python3 python/tutorials/03-matrix-multiplication-cpu.py 
triton_cpu_output_with_torch.float32_inputs=tensor([[ 34.1671,  -0.6265,   2.1590,  ..., -24.7347,  45.6670,  12.1024],
        [-12.4534, -18.2695,   5.6328,  ...,   3.7349, -24.7166,  18.7389],
        [ 10.1346,   7.3148, -15.2706,  ...,  33.5417, -18.3999, -61.9606],
        ...,
        [-25.3489,  16.8383,  25.1225,  ...,  22.5323, -34.2459,  22.0001],
        [  9.3619,  47.0127,  12.2615,  ..., -32.7080, -19.9729,   7.6856],
        [-12.7559, -20.7132,  14.4755,  ...,  23.1968, -14.5273,  19.9374]])
torch_cpu_output_with_torch.float32_inputs=tensor([[ 34.1671,  -0.6265,   2.1590,  ..., -24.7347,  45.6670,  12.1024],
        [-12.4534, -18.2695,   5.6328,  ...,   3.7349, -24.7166,  18.7390],
        [ 10.1346,   7.3148, -15.2706,  ...,  33.5417, -18.3999, -61.9606],
        ...,
        [-25.3489,  16.8383,  25.1225,  ...,  22.5323, -34.2459,  22.0001],
        [  9.3619,  47.0127,  12.2615,  ..., -32.7080, -19.9729,   7.6856],
        [-12.7559, -20.7132,  14.4755,  ...,  23.1968, -14.5273,  19.9374]])
✅ TritonCPU and TorchCPU match
matmul-performance-fp32 (BLOCK_SIZE_M=32, BLOCK_SIZE_N=32, BLOCK_SIZE_K=32, GROUP_SIZE_M=8):
         M       N       K  TritonCPU 1   TritonCPU     TorchCPU
0    256.0   256.0   256.0     3.498078   49.695028   119.304407
1    384.0   384.0   384.0     3.566519   87.075222   129.384039
2    512.0   512.0   512.0     3.533186   95.162003   328.395512
3    640.0   640.0   640.0     3.518112  157.181118  1167.856332
4    768.0   768.0   768.0     3.478274  122.914360   874.587610
5    896.0   896.0   896.0     3.436000  203.076546  1171.739504
6   1024.0  1024.0  1024.0     3.439377  224.565503  1906.239565
7   1152.0  1152.0  1152.0     3.471396  199.340181  2920.473969
8   1280.0  1280.0  1280.0     3.384347  144.589168    61.136822
9   1408.0  1408.0  1408.0     3.329353  159.479037  2655.169267
10  1536.0  1536.0  1536.0     3.421107  150.505174  2323.931550
11  1664.0  1664.0  1664.0     3.367326  237.912040  2942.447208
12  1792.0  1792.0  1792.0     3.376185  162.921996    79.129514
13  1920.0  1920.0  1920.0     3.308813  176.119590   103.867430
14  2048.0  2048.0  2048.0     3.366153  161.267611   110.504712
15  2176.0  2176.0  2176.0     3.382672  239.158536   570.182579
16  2304.0  2304.0  2304.0     3.378930  241.075954  4500.999939
17  2432.0  2432.0  2432.0     3.255841  208.675597  3314.278067
18  2560.0  2560.0  2560.0     3.331287  244.037487   558.830061
```

**Comment by ienkovich** [comment]
The patch looks good! But I don't see a reason to have `driver.cpp` now. Can we completely remove it?

**Comment by Kuigesi** [comment]
> The patch looks good! But I don't see a reason to have `driver.cpp` now. Can we completely remove it?

Thx ilya for the review. Sorry for the late reply, I was busy with writing review doc the past days. Yes, I think the driver.cpp can be completely removed. I also see that there is a new static compilation PR opened. I will test them on my arm servers and mac.

**Comment by Kuigesi** [comment]
PR Closed after static compilation is merged.

**Pull request closed without merging**
