### PR TITLE
Rebase on upstream [just running tests in this PR; no need to review]

### PR DESCRIPTION
**Pull request by int3**
needed for compatibility with latest pytorch

### CODE REVIEW

**Comment by int3** [comment]
oh huh, I guess it won't run the CI if there are merge conflicts

**Comment by ienkovich** [comment]
I was just doing a similar rebase today. Note that updated LLVM requires significant changes in AMX lowering pass. I have those changes, but they apply on top of #186. There are also other changes to pass tests. My version is in `ienkovich/main-rebased` branch.

**Comment by int3** [comment]
Ah, welp, race condition :/

Alright you can go ahead and land yours

**Comment by ienkovich** [comment]
> oh huh, I guess it won't run the CI if there are merge conflicts

You can create a copy of Triton's main branch in our repo and then make PR against it to check our rebased main in CI. See #188

**Pull request closed without merging**
